const config = {
  PORT: process.env.PORT,
  DB_URL: process.env.DB_URL,
  JWT_SECRET: process.env.JWT_SECRET,
  DIGITALOCEAN_IMAGE: {
    BUCKET_NAME: "imagesecommerce",
    END_POINT: "https://blr1.digitaloceanspaces.com",
    ACCESS_KEY_ID: "DO00MM6C2ZRAVW8AHYBW",
    SECRET_ACCESS_KEY: "SWMGOtMw7AHfT7UfjRfzUvjTESg5BIJ05zAwUJvvux4",
    REGION: "blr1",
  },
  USER_TYPE: {
    SA: "SA", //This is super admin
    U: "U", //This is user
    A: "A", //This is admin.
  },
  API: {
    USER: {
      UPDATE_USER: "/update-user",
      SIGNIN_USER: "/signin-user",
      SIGNUP_USER: "/signup-user",
      GET_USER_DETAILS: "/get-user-details",
      DELETE_USER: "/delete-user",
    },
    ADMIN: {
      ACCOUNT: {
        VIEW_ACCOUNT: "/view_account",
      },
      COUNTRY: {
        ADD_COUNTRY: "/add_country",
        VIEW_COUNTRY: "/view_country",
        EDIT_COUNTRY: "/edit_country",
        DELETE_COUNTRY: "/delete_country",
        ASSIGNED_COUNTRY: "/assigned_country",
        UNASSIGNED_COUNTRY: "/unassigned_country",
        ADD_COUNTRY_FROM_CSV: "/add_country_from_csv",
        SEND_COUNTRY_TO_CSV: "/export_country_to_csv",
        VIEW_ALL_COUNTRY: "/view_all_country",
      },
      STATE: {
        ADD_STATE: "/add_state",
        VIEW_STATE: "/view_state",
        EDIT_STATE: "/edit_state",
        DELETE_STATE: "/delete_state",
        ASSIGNED_STATE: "/assigned_state",
        UNASSIGNED_STATE: "/unassigned_state",
        ADD_STATE_FROM_CSV: "/add_state_from_csv",
        SEND_STATE_TO_CSV: "/export_state_to_csv",
        VIEW_ALL_STATE: "/view_all_state",
      },
      CATEGORY: {
        ADD_CATEGORY: "/add_category",
        EDIT_CATEGORY: "/edit_category",
        VIEW_CATEGORY: "/view_category",
        DELETE_CATEGORY: "/delete_category",
        ASSIGNED_CATEGORY: "/assigned_category",
        UNASSIGNED_CATEGORY: "/unassigned_category",
        VIEW_ALL_CATEGORY: "/view_all_category",
        GET_CATEGORY_DETAILS: "/get_category_details",
        VIEW_PRODUCT_CATEGORY: "/view_product_category",
        VIEW_CATEGORY_PRODUCT: "/view_category_product",
        ADD_CATEGORY_FROM_CSV: "/add_category_from_csv",
        ADD_CATEGORY_HEADER_FOOTER_FROM_CSV:
          "/add_category_header_footer_from_csv",
        UPDATE_HEADER_FOOTER: "/update_header_footer",
        ASSIGN_PRODUCT_CATEGORY: "/assign_product_category",
        UNASSIGN_PRODUCT_CATEGORY: "/unassign_product_category",
        SEND_CATEGORY_DATA_TO_CSV: "/export_category_to_csv",
      },
      CATEGORY_META: {
        ADD_CATEGORY_META: "/add_category_meta",
        EDIT_CATEGORY_META: "/edit_category_meta",
        VIEW_CATEGORY_META: "/view_category_meta",
        DELETE_CATEGORY_META: "/delete_category_meta",
        ADD_META_FROM_CSV: "/add_meta_from_csv",
        SEND_META_TO_CSV: "/export_meta_to_csv",
        GET_META_DETAILS: "/get_meta_details",
      },
      PRODUCT: {
        ADD_PRODUCT: "/add_product",
        EDIT_PRODUCT: "/edit_product",
        DELETE_PRODUCT: "/delete_product",
        VIEW_PRODUCT: "/view_product",
        UPDATE_PRODUCT_GLOBAL_ATTRIBUTES: "/update_product_global_attributes",
        VIEW_GLOBAL_LOCAL_ATTRIBUTES: "/view_global_local_attributes",
        ASSIGNED_AND_UNASSIGNED_PRODUCT: "/assigned_and_unassigned_product",
        VIEW_ALL_PRODUCT: "/view_all_product",
        ADD_NEW_PRODUCT_FROM_CSV: "/add_new_product_from_csv",
        ADD_PRODUCT_FROM_CSV: "/add_product_from_csv",
        ADD_PRODUCT_LINK_FROM_CSV: "/add_product_link_from_csv",
        ADD_PRODUCT_CATEGORY_FROM_CSV: "/add_product_category_from_csv",
        ADD_RELATED_PRODUCT_FROM_CSV: "/add_related_product_from_csv",
        ADD_GLOBAL_ATTRIBUTE_FROM_CSV: "/add_global_attribute_product_from_csv",
        ADD_LOCAL_ATTRIBUTE_FROM_CSV: "/add_local_attribute_product_from_csv",
        ADD_PRODUCT_STATISTICS_FROM_CSV: "/add_product_statistics_from_csv",
        SEND_PRODUCT_TO_CSV: "/export_product_to_csv",
        VIEW_PRODUCT_DETAILS: "/view_product_details",
        VIEW_RELATED_PRODUCTS: "/view_related_products",
      },
      PRODUCT_META: {
        ADD_PRODUCT_META: "/add_product_meta",
        EDIT_PRODUCT_META: "/edit_product_meta",
        DELETE_PRODUCT_META: "/delete_product_meta",
        VIEW_PRODUCT_META: "/view_product_meta",
        GET_PRODUCT_META_DETAILS: "/get_product_meta_details",
        ADD_PRODUCT_META_FROM_CSV: "/add_product_meta_from_csv",
        SEND_PRODUCT_META_TO_CSV: "/export_product_meta_to_csv",
      },
      TEMPLATE: {
        VIEW_TEMPLATE: "/view_template",
        ADD_TEMPLATE: "/add_template",
        EDIT_TEMPLATE: "/edit_template",
        DELETE_TEMPLATE: "/delete_template",
        ADD_TEMPLATE_FROM_CSV: "/add_template_from_csv",
        ADD_TEMPLATE_ATTRIBUTE_FROM_CSV: "/add_template_attribute_from_csv",
        ASSGINED_UNASSIGNED_TEMPLATE: "/assigned_and_unassigned_template",
        VIEW_ALL_TEMPLATE: "/view_all_template",
      },
      ATTRIBUTES: {
        ADD_ATTRIBUTES: "/add_attributes",
        EDIT_ATTRIBUTES: "/edit_attributes",
        VIEW_ATTRIBUTES: "/view_attributes",
        DELETE_ATTRIBUTES: "/delete_attributes",
        ASSIGNED_ATTRIBUTES: "/assigned_attributes",
        UNASSIGNED_ATTRIBUTES: "/unassigned_attributes",
        VIEW_GLOBAL_ATTRIBUTE_PRODUCT: "/view_global_attribute_product",
        ADD_PRODUCT_GLOBAL_ATTRIBUTES: "/add_product_global_attributes",
        DELETE_GLOBAL_ATTRIBUTE_PRODUCT: "/delete_global_attribute_product",
        ADD_ATTRIBUTES_FROM_CSV: "/add_attributes_from_csv",
        ADD_ATTRIBUTES_OPTIONS_FROM_CSV: "/add_attributes_options_from_csv",
        SEND_ATTRIBUTES_TO_CSV: "/send_attributes_from_csv",
        CRUD_ATTRIBUTES_OPTION: "/crud_attributes_options",
      },
      LOCAL_ATTRIBUTES: {
        ADD_LOCAL_ATTRIBUTES: "/add_local_attributes",
        EDIT_LOCAL_ATTRIBUTES: "/edit_local_attributes",
        DELETE_LOCAL_ATTRIBUTES: "/delete_local_attributes",
        ADD_LOCAL_ATTRIBUTES_FROM_CSV: "/add_local_attributes_from_csv",
        ADD_LOCAL_ATTRIBUTE_OPTION_FROM_CSV:
          "/add_local_attribute_option_from_csv",
        SEND_LOCAL_ATTRIBUTES_TO_CSV: "/send_local_attributes_from_csv",
        CRUD_LOCAL_ATTRIBUTES_OPTION: "/crud_local_attributes_options",
      },
      SHIPPING_MESSAGE: {
        ADD_SHIPPING_MESSAGE: "/add_shipping_message",
        EDIT_SHIPPING_MESSAGE: "/edit_shipping_message",
        VIEW_SHIPPING_MESSAGE: "/view_shipping_message",
        DELETE_SHIPPING_MESSAGE: "/delete_shipping_message",
        ASSIGNED_SHIPPING_MESSAGE: "/assigned_shipping_message",
        UNASSIGNED_SHIPPING_MESSAGE: "/unassigned_shipping_message",
        VIEW_ALL_SHIPPING_MESSAGE: "/view_all_shipping_message",
        ADD_SHIPPING_MESSAGE_FROM_CSV: "/add_shipping_message_from_csv",
        SEND_SHIPPING_MESSAGE_TO_CSV: "/send_shipping_message_from_csv",
      },
    },
  },
  ROUTER: {
    USER: "/users",
    PRODUCT: "/product",
    PRODUCT_META: "/product_meta",
    ATTRIBUTES: "/attributes",
    TEMPLATE: "/template",
    LOCAL_ATTRIBUTES: "/local_attributes",
    SHIPPING_MESSAGE: "/shipping_message",
    STATIC_TEMPLATE: "/static-template",
    SHIPPING_METHOD: "/shipping-method",
    MARKETINGFEED: "/marketing-feed",
    METALTYPE: "/metal-type",
    CATEGORY: "/category",
    CATEGORY_META: "/category_meta",
    SHORT_PRODUCT: "/short-product",
  },
  COLLECTION: {
    USER: "users",
    COUNRTY: "country",
    STATE: "state",
    CATEGORY: "category",
    CATEGORY_META: "category_meta",
    PRODUCT: "product",
    PRODUCT_META: "product_meta",
    ASSIGN_CAT_PRD: "assign_cat_prd",
    ATTRIBUTES: "attributes",
    LOCAL_ATTRIBUTES: "local_attributes",
    SHIPPING_MESSAGE: "shipping_message",
    TEMPLATE: "template",
    BILLING_ADDRESS: "billing_address",
    SHIPPING_ADDRESS: "shipping_address",
    STATIC_TEMPLATE: "static-template",
    SUPPLIER: "supplier",
    SHIPPING_METHOD: "shipping-method",
    CMS: "cms",
    MARKETINGFEED: "marketing-feed",
    CART: "cart",
    ORDER: "order",
    PAYMENT_METHOD: "payment-method",
    WISHLIST: "wish-list",
    PROMOTIONAL_MESSAGE: "promotional-message",
    HOME_CMS: "home-cms",
    FAQ: "faq",
    PRODUCT_CATEGORY: "product-category",
    METALTYPE: "metal-type",
    PRODUCT_ATTRIBUTE: "product-attribute",
    RELATED_PRODUCTS: "related-products",
  },
  REGEXP: {
    NAME: /^([\w]{1,})+\s+([\w\s]{1,})+$/i,
    EMAIL:
      /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
    PASSWORD:
      /^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@$!%*?#&^_()+-/])([a-zA-Z0-9@$!%*?#&^_()+-/]{8,})$/,
    CONTACT_NO: /^\d{10}$/,
    OBJECT_ID: /^(?=[a-f\d]{24}$)(\d+[a-f]|[a-f]+\d)/i,
  },
  SCHEMA_MESSAGE: {
    _ID: {
      INVALID: "Invalid _id",
      ID: "_id should not be empty!",
    },
    SEARCH: "search field can not be empty!",
    CSV: {
      CSV_NAME: "csv file should be selected",
      CSV_SIZE: "csv file size is too large",
    },
    PAGINATION: {
      STARTING_AFTER: "starting after parameter is missing",
      LIMIT: "limit parameter is missing",
    },
    META: {
      META_TITLE: "meta title should not be empty!",
      META_KEYWORD: "Meta keyword should not be empty!",
      META_DESC: "Meta description should not be empty!",
      META_ID: "Meta _id should be valid!",
      META_CONTENT: "Meta content should not be empty!",
    },
    USER: {
      NAME: "name field can not be empty! ",
      VALID_NAME: "name should have first and last name",
      EMAIL: "email field can not be empty! ",
      VALID_EMAIL: "email should be valid like person@gmail.com",
      PASSWORD: "password field can not be empty! ",
      VALID_PASSWORD: "password should be a valid password",
      CONTACT_NO: "contact no. should be 10 digit",
      USER_TYPE: "user_type field can not be empty!",
    },
    COUNTRY: {
      COUNTRY_NAME: "country name should not be empty!",
      COUNTRY_CODE: "country code should not be empty!",
    },
    STATE: {
      STATE_NAME: "state name should not be empty!",
      STATE_CODE: "state code should not be empty!",
      STATE_ID: "state id should not be empty!",
      STATE_ID_INVALID: "state id is invalid!",
    },
    CATEGORY: {
      CATEGORY_NAME: "category name should not be empty!",
      CATEGORY_CODE: "category code should not be empty!",
      CATEGORY_PAGE_CONTENT: "category page content should not be empty!",
      CATEGORY_ID: "category_id is not valid!",
    },
    CATEGORY_META: {
      CATEGORY_ID: "At least one category should be selected!",
    },
    PRODUCT: {
      //main part
      NAME: "product name should not be empty!",
      PRICE: "product price should not be empty!",
      SKU: "product sku should not be empty!",
      MSRP: "product msrp should not be empty!",
      //image part
      ALTERNATIVE_IMAGE: "alternative image should not be empty!",
    },
    PRODUCT_META: {
      PRODUCT_ID: "At least one product should be select for product meta!",
    },
    ASSIGN_CAT_PRD: {
      PRODUCT_ID:
        "At least one product should be select for assign category product!",
      CATEGORY_ID:
        "At least one category should be selected for assign category product!",
    },
    ATTRIBUTES: {
      ATTRIBUTES_PROMPT: "prompt should not be empty!",
      ATTRIBUTES_CODE: "code should not be empty!",
      ATTRIBUTES_TYPE: "type should not be empty!",
      ATTRIBUTES_OPTION: "attribute option should not be empty!",
      ATTRIBUTES_OPTION_PRICE: "price should not be empty!",
      ATTRIBUTES_OPTION_DEFAULT: "default should not be empty!",
      ATTRIBUTES_OPTION_REQUIRED: "required should not be empty!",
    },
    SHIPPING_MESSAGE: {
      CODE: "shipping code should not be empty!",
      MESSAGE: "shipping message should not be empty!",
      DAYS: "shipping days should not be empty!",
      FREE: "shipping free should not be empty!",
      ORDER: "shipping custom order should not be empty!",
      COUNTRY: "shipping country should not be empty!",
    },
  },
  RESPONSE: {
    DATA: "Data already exsist.",
    FAILED: "Error occurred. Try again.",
    WARNING: "Some warning",
    ADD: "Data added successfully.",
    EDIT: "Data updated successfully.",
    DELETE: "Data deleted successfully.",
    FOUND: "Data(s) found.",
    NOT_FOUND: "No data found.",
    UPLOAD_SUCCESS: "Media uploaded successfully.",
    UPLOAD_ERROR: "Error occour csv file is not in correct format",
    MAIL_SENT: "An email has been sent to your account.",
    INVALID_USER: "invalid user",
    EMAIL_EXISTS: "Email already exists",
    NO_USER_EXISTS: "User was not found. Please sign up.",
    INVALID_CREDENTIALS: "Incorrect username/password",
    LOGIN_SUCCESS: "Login Successful!",
    LOGOUT_SUCCESS: "Logout Successful!",
    PASSWORDS_DONT_MATCH: "Error: Passwords don't match",
    RESET_CODE_EXPIRED: "Error: Reset Password code expired",
    ACCESS_DENIED: "Don't have access!",
    USER_TOKEN_NOT_FOUND: "user token is mandatory!",
    OTP_GENERATION_FAILED: "opt generation failed!",
    EMAIL_VERIFICATION_SUCCESSFUL: "Email successfully verified",
    EMAIL_VERIFICATION_FAILED: "Email verification failed",
  },
};

export default { ...config };
